name: adme-tox-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit>=2023.9.1  # Use a newer version of RDKit
  - pandas<2.2  # Use a compatible pandas version
  - pip
  - pip:
    - streamlit==1.39.0
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - plotly
    - Pillow
    - pubchempy
    - py3Dmol
    - joblib
    - requests
    - json5
    - PyTDC
